export const LOAD_WALLETS_SUCCESS = 'LOAD_WALLETS_SUCCESS';
export const LOAD_WALLETS_FAILURE = 'LOAD_WALLETS_FAILURE';

export const LOAD_RATES_SUCCESS = 'LOAD_RATES_SUCCESS';
export const LOAD_RATES_FAILURE = 'LOAD_RATES_FAILURE';

export const UPDATE_EXCHANGE_PARAMETERS = 'UPDATE_EXCHANGE_PARAMETERS';
export const INITIATE_EXCHANGE = 'INITIATE_EXCHANGE';
export const EXCHANGE_SUCCESS = 'EXCHANGE_SUCCESS';
export const EXCHANGE_FAILURE = 'EXCHANGE_FAILURE';

export const LOAD_EXCHANGE_HISTORY_SUCCESS = 'LOAD_EXCHANGE_HISTORY_SUCCESS';
export const LOAD_EXCHANGE_HISTORY_FAILURE = 'LOAD_EXCHANGE_HISTORY_FAILURE';
