export const LOAD_WALLETS_SUCCESS = 'LOAD_WALLETS_SUCCESS';
export const LOAD_WALLETS_FAILURE = 'LOAD_WALLETS_FAILURE';
export const LOAD_RATES_SUCCESS = 'LOAD_RATES_SUCCESS';
export const LOAD_RATES_FAILURE = 'LOAD_RATES_FAILURE';
